<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<OutputPath>../Editor/Resources/Scripts</OutputPath>
		<BaseIntermediateOutputPath>../Editor/Resources/Scripts/Intermediates/</BaseIntermediateOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Coral.Managed">
			<HintPath>../Editor/DotNet/Coral.Managed.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
