-- Standalone workspace for the sample game's C# scripts, generated by scripts/Setup.py and
-- built on demand by the editor's ScriptBuilder. It references the pre-built ScriptCore.dll
-- (from Editor/Resources/Scripts) and Coral.Managed (from Editor/DotNet) - it does NOT rebuild
-- them, so Coral.Managed is not pulled into this workspace.
local LuxEngineRootDir = '../../../..'
include (LuxEngineRootDir .. "/vendor/premake_customization/solution_items.lua")

workspace "LuxSample"
	startproject "LuxSample"

	configurations { "Debug", "Release", "Dist" }
	flags { "MultiProcessorCompile" }

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

project "LuxSample"
	kind "SharedLib"
	language "C#"
	dotnetframework "net9.0"
	clr "Unsafe"

	targetdir ("Binaries")
	objdir ("Intermediates")

	vsprops {
		AppendTargetFrameworkToOutputPath = "false",
		Nullable = "disable",
		EnableDynamicLoading = "true",
	}

	files {
		"Source/**.cs",
		"Properties/**.cs"
	}

	-- Explicit .dll paths so premake emits <Reference> with a HintPath (bare names + libdirs
	-- don't resolve for SDK-style C# on this premake build). These are built beforehand by the
	-- main Lux.sln (ScriptCore) and Core's postbuild (Coral.Managed).
	links {
		LuxEngineRootDir .. "/Editor/Resources/Scripts/ScriptCore.dll",
		LuxEngineRootDir .. "/Editor/DotNet/Coral.Managed.dll"
	}

	filter "configurations:Debug"
		optimize "Off"
		symbols "Default"

	filter "configurations:Release"
		optimize "On"
		symbols "Default"

	filter "configurations:Dist"
		optimize "Full"
		symbols "Off"
