name: Build LuxEngine

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - 'features/**' # Glob pattern for any branch starting with 'features/'
  pull_request:
    branches:
      - master
      - dev

env:
  GITHUB_WORKSPACE: ${{ github.workspace }}
  SOLUTION_FILE_PATH: Lux.sln
  BUILD_PLATFORM: Mixed Platforms
  PREMAKE_GENERATOR: vs2022

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release, Dist]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.11'

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.4.0
        with:
          vulkan_version: 1.4.335.0
          optional_components: com.lunarg.vulkan.vma, com.lunarg.vulkan.debug, com.lunarg.vulkan.glm
          install_runtime: true
          cache: true
          stripdown: true

          install_swiftshader: false
          install_lavapipe: false

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: 'x64'

      - name: Setup
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd scripts
          python Setup.py ${{ env.PREMAKE_GENERATOR }}

      - name: Prepare logs
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: New-Item -ItemType Directory -Force logs

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          MSBuild "${{ env.SOLUTION_FILE_PATH }}" /m "/p:Configuration=${{ matrix.configuration }}" "/p:Platform=${{ env.BUILD_PLATFORM }}" /fl "/flp:logfile=logs\Build-${{ matrix.configuration }}.log;verbosity=normal"

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.configuration }}
          path: logs/*.log
          if-no-files-found: ignore
